### ISSUE TITLE
pt to px in cairo output

### ISSUE THREAD

**Issue by Zverik** [Zverik/Nik4#13]
Since cairo always writes dimensions in pt (see [this issue](https://github.com/mapnik/mapnik/issues/2269)), they have to be converted in nik4: divide by 1.25.

**Comment by jekhor** [comment]
А почему коммит, это исправляющий, был впоследствии выпилен? Баг остался.

**Comment by Zverik** [comment]
Да, мапник вообще не задумывается о конвенциях, просто шарашит всё в абстрактных числах, т.е. здесь в пунктах.
