### ISSUE TITLE
NameError with -c option

### ISSUE THREAD

**Issue by ugoertz** [Zverik/Nik4#18]
Hello,

thanks for your work on nik4, it is very useful. There seems to be a small problem with the `-c` option, though:

```
$ nik4.py -c 7.5 52.0 -s 5000 --margin 10 --ppi 300 -a 4 mapnik.xml print.png
Traceback (most recent call last):
  File "/home/ug/.virtualenvs/maps/bin/nik4.py", line 289, in <module>
    scale = scale / math.cos(math.radians(center.y))
NameError: name 'center' is not defined
```

If I understand correctly, `center.y` should be replaced by `options.center[1]`, at least this makes the code run through (or is it necessary to apply some transform here?).

**Comment by Zverik** [comment]
Thanks, fixed it and uploaded version 1.5.2 to pypi.
