### ISSUE TITLE
Publish release tags

### ISSUE THREAD

**Issue by sebastic** [Zverik/Nik4#24]
Please publish release tags for new versions.

This well help downstream users to be notified of new releases.

**Comment by Zverik** [comment]
Did that for the current release, will try not to forget when publishing next releases :)

**Comment by sebastic** [comment]
Thanks I've updated the [nik4 Debian package](https://tracker.debian.org/pkg/nik4) with the tagged release to have it use the proper version.

**Comment by Zverik** [comment]
Thanks for supporting the package!
I'd drop the `.py` extension in `setup.py`, but I could not find a way.
As for the python3 issue, I'll test and fix it in the next couple of days.
