### ISSUE TITLE
Stale link in documentation

### ISSUE THREAD

**Issue by sebastic** [Zverik/Nik4#41]
As reported by Wookey in [Debian Bug #985764](https://bugs.debian.org/985764):
> The file /usr/share/doc/nik4/README.md.gz contains a link to instructions at 
> http://switch2osm.org/loading-osm-data/
> which no longer exists.
> I'm not sure what it should be replaced with.

archive.org still has a few copies, but it should probably be removed.

**Comment by Zverik** [comment]
Thanks for the notice, replaced the link with a fresher one.
