### ISSUE TITLE
Where to find osm.xml style file?

### ISSUE THREAD

**Issue by PanderMusubi** [Zverik/Nik4#43]
Where to find osm.xml style file? I can only find the uncompiled sources: https://github.com/openstreetmap/mapnik-stylesheets

**Comment by Zverik** [comment]
The latest version of the style is in [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto). It needs a bit of work to be built, but it's all described there in `install.md`. And there are some alternatives listed in the readme.
